/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Cliente;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nigga
 */
public class FClientes extends javax.swing.JFrame {

    /**
     * Creates new form FClientes
     */
     private static FClientes instancia;
     private DefaultTableModel dtm;
     private Cliente cl;
     private static final String[]nombreColumnas = {"RUT ","NOMBRE ","DIRECCION","EMPRESA","TELEFONO","MAIL","TIPO"};
    private FClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cl = new Cliente();
        this.tf_rutCliente.setEnabled(false);
        this.tf_nombreCliente.setEnabled(false);
        this.tf_direccionCliente.setEnabled(false);
        this.tf_empresaCliente.setEnabled(false);
        this.tf_telefonoCliente.setEnabled(false);
        this.tf_mail.setEnabled(false);
        this.bt_añadir.setEnabled(true);
        this.bt_guardarNuevoCliente.setEnabled(false);
        
    }
        public static FClientes getInstancia() {
        if (instancia == null) {
            instancia = new FClientes();
        }
        return instancia;

    }
        
        private void cargarTabla(){
        ArrayList<Cliente> r;
        Iterator<Cliente> iterador;
        Cliente alguno;
        Object[][] data;
        int index = 0;
            try{
                r = new Cliente().cargar();
                iterador = r.iterator();
        //pasa los datos a la tabla
                data = new Object[r.size()][6];
                while(iterador.hasNext()){
                alguno = iterador.next();
                data[index][0] = alguno.getRutCliente();
                data[index][1] = alguno.getNombreCliente();
                data[index][2] = alguno.getDireccionCliente();
                data[index][3] = alguno.getEmpresaCliente();
                data[index][4] = alguno.getTelefonoCliente();
                data[index][5] = alguno.getMailCliente();
               
                index++;
            }
            dtm = new DefaultTableModel(){
      public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        dtm.setDataVector(data, nombreColumnas);
        
        this.jt_registros.setModel(dtm);
//        } catch (IOException e) {
//            System.out.println("Error de E/S. Descripción : " + e.getMessage());
        } catch (ClassNotFoundException e) {
            System.out.println("Error de conversión. Descripción : " + e.getMessage());
        } catch (InstantiationException e) {
            System.out.println("Error de instanciación. Descripción : " + e.getMessage());
        } catch (IllegalAccessException e) {
            System.out.println("Error de acceso. Descripción : " + e.getMessage());
        } catch (SQLException e) {
            System.out.println("Error a nivel de SQL. Descripción : " + e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pu_editar = new javax.swing.JPopupMenu();
        mi_editar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_registros = new javax.swing.JTable();
        bt_abonar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_rutCliente = new javax.swing.JTextField();
        tf_nombreCliente = new javax.swing.JTextField();
        tf_empresaCliente = new javax.swing.JTextField();
        tf_telefonoCliente = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        tf_direccionCliente = new javax.swing.JTextField();
        bt_guardarNuevoCliente = new javax.swing.JButton();
        bt_añadir = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();

        mi_editar.setText("Editar");
        mi_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_editarActionPerformed(evt);
            }
        });
        pu_editar.add(mi_editar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de los Clientes"));

        jt_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Direccion", "Empresa", "Telefono", "Email"
            }
        ));
        jt_registros.setComponentPopupMenu(pu_editar);
        jt_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jt_registrosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jt_registros);

        bt_abonar.setText("ABONAR");
        bt_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_abonarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_abonar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_abonar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        jLabel1.setText("Rut");

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        jLabel4.setText("Empresa");

        jLabel5.setText("Telefono");

        jLabel6.setText("Email");

        bt_guardarNuevoCliente.setText("Guardar");
        bt_guardarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarNuevoClienteActionPerformed(evt);
            }
        });

        bt_añadir.setText("Añadir +");
        bt_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_añadirActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_rutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(tf_empresaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bt_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_guardarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(302, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_empresaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(tf_rutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_guardarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_añadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_abonarActionPerformed
            FAbono mi_ventana = FAbono.getInstancia();
        mi_ventana.setVisible(true);

    }//GEN-LAST:event_bt_abonarActionPerformed

    private void bt_guardarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarNuevoClienteActionPerformed
        
        this.cl.setRutCliente(Integer.parseInt(this.tf_rutCliente.getText()));
        this.cl.setNombreCliente(this.tf_nombreCliente.getText());
        this.cl.setDireccionCliente(this.tf_direccionCliente.getText());
        this.cl.setEmpresaCliente(this.tf_empresaCliente.getText());
        this.cl.setTelefonoCliente(Integer.parseInt(this.tf_telefonoCliente.getText()));
        this.cl.setMailCliente(this.tf_mail.getText());
        
        try {
            
            this.cl.grabar();
            JOptionPane.showMessageDialog(null, "Registro guardado con exito");
            this.tf_rutCliente.setText("");
            this.tf_nombreCliente.setText("");
            this.tf_direccionCliente.setText("");
            this.tf_empresaCliente.setText("");
            this.tf_telefonoCliente.setText("");
            this.tf_mail.setText("");
            
            this.tf_rutCliente.setEnabled(false);
            
            this.bt_guardarNuevoCliente.setEnabled(false);
           
            this.cargarTabla();
        } catch (java.lang.ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        } catch (java.lang.IllegalAccessException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        } catch (java.lang.InstantiationException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
            //        } catch (ErrorNegocio e) {
            //            JOptionPane.showMessageDialog(null,"Descripcion : " + e.getMessage());
        }
        
               
    }//GEN-LAST:event_bt_guardarNuevoClienteActionPerformed

    private void bt_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_añadirActionPerformed
        this.tf_rutCliente.setEnabled(true);
        this.tf_nombreCliente.setEnabled(true);
        this.tf_direccionCliente.setEnabled(true);
        this.tf_empresaCliente.setEnabled(true);
        this.tf_telefonoCliente.setEnabled(true);
        this.tf_mail.setEnabled(true);
        this.bt_guardarNuevoCliente.setEnabled(true);
    }//GEN-LAST:event_bt_añadirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try{
            this.cl.cargar();
            this.cargarTabla();
        
         } catch (java.lang.ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        } catch (java.lang.IllegalAccessException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        } catch (java.lang.InstantiationException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(null, "Descripcion : " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void mi_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_editarActionPerformed
        this.tf_rutCliente.setText(String.valueOf(this.cl.getRutCliente()));
        this.tf_nombreCliente.setText(this.cl.getNombreCliente());
        this.tf_direccionCliente.setText(this.cl.getDireccionCliente());
        this.tf_empresaCliente.setText(this.cl.getEmpresaCliente());
        this.tf_telefonoCliente.setText(String.valueOf(this.cl.getTelefonoCliente()));
        this.tf_mail.setText(this.cl.getMailCliente());
        
        //habilitamos nuevamente
        this.tf_rutCliente.requestFocus();
        this.tf_rutCliente.setEnabled(true);
        this.tf_nombreCliente.setEnabled(true);
        this.tf_direccionCliente.setEnabled(true);
        this.tf_empresaCliente.setEnabled(true);
        this.tf_telefonoCliente.setEnabled(true);
        this.tf_mail.setEnabled(true);
        this.bt_guardarNuevoCliente.setEnabled(true);
        
        
        
        
        
        
    }//GEN-LAST:event_mi_editarActionPerformed

    private void jt_registrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_registrosMousePressed
        int fila = this.jt_registros.rowAtPoint(evt.getPoint());
        int columna = this.jt_registros.columnAtPoint(evt.getPoint());
        /* Muestra los datos en la ventana de edición si corresponde */
        if ((fila > -1) && (columna > -1)) {
            this.cl.setRutCliente((Integer) this.dtm.getValueAt(fila, 0));
            this.cl.setNombreCliente((String) this.dtm.getValueAt(fila, 1));
            this.cl.setDireccionCliente((String) this.dtm.getValueAt(fila, 2));            
            this.cl.setEmpresaCliente((String) this.dtm.getValueAt(fila, 3));
            this.cl.setTelefonoCliente((Integer) this.dtm.getValueAt(fila, 4));
            this.cl.setMailCliente((String) this.dtm.getValueAt(fila, 5));
            this.cl.setTipoCliente((String) this.dtm.getValueAt(fila, 6));
                
        }      
               
        
        
    }//GEN-LAST:event_jt_registrosMousePressed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FClientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_abonar;
    private javax.swing.JButton bt_añadir;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_guardarNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_registros;
    private javax.swing.JMenuItem mi_editar;
    private javax.swing.JPopupMenu pu_editar;
    private javax.swing.JTextField tf_direccionCliente;
    private javax.swing.JTextField tf_empresaCliente;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nombreCliente;
    private javax.swing.JTextField tf_rutCliente;
    private javax.swing.JTextField tf_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
